# Generated by Django 2.2 on 2021-03-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, '贪污'), (2, '受贿'), (3, '出卖商业机密'), (4, '日常检查')], default=4, verbose_name='案件类别')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.TextField(default='', verbose_name='活动描述')),
            ],
            options={
                'verbose_name': '案件',
                'verbose_name_plural': '案件',
            },
        ),
    ]
